### PR TITLE
Use pre-commit to verify commit message format

### PR DESCRIPTION
**Pull request by wenzowski**
[git_commit_2x](https://xkcd.com/1296/)

## Solution: use pre-commit to verify commit message format
**Developer action is required to enable this feature locally.**

The `commit-msg` hook must be installed to ensure commit messages
conform to community standards:

```bash
pre-commit install --hook-type commit-msg
```

The project [pre-commit] framework configuration
has been updated to include hooks for [gitlint] and a [`.gitlint`]
configuration file has been added to control its [rules].

[pre-commit]: https://pre-commit.com/
[gitlint]: http://jorisroovers.com/gitlint/
[`.gitlint`]: http://jorisroovers.com/gitlint/configuration/
[rules]: http://jorisroovers.com/gitlint/rules/

### CODE REVIEW

**Comment by wenzowski** [comment]
This probably needs [CI config](http://jorisroovers.com/gitlint/#using-gitlint-in-a-ci-environment) before merging...

**Comment by matthieu-foucault** [comment]
This should be combined with using committizen to write our commit messages

**Comment by wenzowski** [comment]
This might tie in with a [good contributing document](https://github.com/deis/deis/blob/master/CONTRIBUTING.md) too

**Comment by wenzowski** [comment]
contributing doc underway in https://github.com/bcgov/cas-ciip-portal/pull/117

**Comment by wenzowski** [comment]
@matthieu-foucault either way we're implementing https://www.conventionalcommits.org/ right? I'm not super familiar with [cz-cli](http://commitizen.github.io/cz-cli/) but I'm happy to take a stab at that unless you have opinions about config setup?

**Comment by matthieu-foucault** [comment]
> @matthieu-foucault either way we're implementing https://www.conventionalcommits.org/ right? I'm not super familiar with [cz-cli](http://commitizen.github.io/cz-cli/) but I'm happy to take a stab at that unless you have opinions about config setup?

Yes we are. `cz-cli` isn't technically required, it just formats the commit messages for you.

**Comment by wenzowski** [comment]
@matthieu-foucault I'd like to make sure these comments are cleaned up before I fix this branch. Lmk if we need to sync on that and tyvm for pitching in here.

@blueQcloud something we should probably put in our Contributing document: the team integrates only on the `develop` branch. This means only the person who created a `feature/*` branch should update it, unless otherwise instructed by the original author.

**Comment by matthieu-foucault** [comment]
@wenzowski You're good to go. I took care of the comments

**Comment by matthieu-foucault** [comment]
The repo still has to be made [comittizen-friendly](https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly) if we want to use git-cz insead of git commit

**Comment by wenzowski** [comment]
had to use a `.czrc` file to adapt the ugly monorepo, but `git-cz` should work

**Comment by wenzowski** [comment]
> instruct all devs to use the pre-commit and/or comittizen
there's currently divergence between the python config (gitlint) and the node config (git-cz) which has me wondering if we shouldn't settle on either comittizen or pre-commit as a process (and not both)

**Comment by matthieu-foucault** [comment]
Perhaps we should use https://github.com/conventional-changelog/commitlint instead of gitlint

**Comment by wenzowski** [comment]
I'll look into that then

**Comment by matthieu-foucault** [comment]
Continuing work in #539

**Comment by matthieu-foucault** [comment]
This actually looks closer to what I was going to do than I thought, not sure why it wasn't merged in the first place.

**Pull request merged**
