### PR TITLE
Fix failing audit CI step

### PR DESCRIPTION
**Pull request by dleard**
- Fixes https://www.npmjs.com/advisories/1219
- I may have done a bad bad thing, or at least this is worth watching as no new version is currently available that is unaffected. So I have rolled this package back to the last unaffected version, which is a beta from a year ago.

This package is only used by storybook

### CODE REVIEW

**Comment by matthieu-foucault** [comment]
@dleard I think that the version you chose is technically affected, but wasn't analyzed by npm as it's a beta. I expect a patch would be released soon given the impact

**Comment by matthieu-foucault** [comment]
see https://github.com/probablyup/markdown-to-jsx/issues/306

**Comment by dleard** [comment]
@matthieu-foucault So is rolling back to this un-analyzed version in order to continue to merge things fine until there is a patch?

**Comment by matthieu-foucault** [comment]
Yeah. I subscribed to the issue linked above to see how things go

**Pull request merged**
