### PR TITLE
Storyshots

### PR DESCRIPTION
**Pull request by dleard**

### CODE REVIEW

**Comment by wenzowski** [comment]
rebased on #83 for review

**Comment by wenzowski** [comment]
@dleard rebased on `develop`

**Comment by dleard** [comment]
@wenzowski I think this needs an ignore script update somewhere, the linter is touching the .storyshots file extensions. I just haven't gotten around to figuring out where

**Comment by wenzowski** [comment]
Eventually, it would be really nice if we could get the entire Storybook layer into its own folder and decoupled from our app.

**Pull request merged**
